let rec_id;
ZOHO.embeddedApp.on("PageLoad",async function(data){
    ZOHO.CRM.UI.Resize({height:"700",width:"1000"})
    lead_id = data.EntityId;
    rec_id = lead_id[0];
    let lead_data = await ZOHO.CRM.API.getRecord({Entity: "Leads", approved: "both", RecordID:rec_id});
    lead_rec = lead_data.data[0];
    document.getElementById('fname').value = lead_rec.First_Name;
    document.getElementById('lname').value = lead_rec.Last_Name;
    document.getElementById('femail').value = lead_rec.Email;
    document.getElementById('unique_id').value = lead_rec.Unique_Lead_ID;
    document.getElementById('camp_name').value = lead_rec.Campaign_Name;
    document.getElementById('lead_source').value = lead_rec.Lead_Source;
    document.getElementById('AD').value = lead_rec.AD_Name;
    document.getElementById('Phone').value = lead_rec.Phone;
    document.getElementById('County').value = lead_rec.County;
    document.getElementById('formname').value = lead_rec.Lead_Form_Name;
    document.getElementById('source').value = lead_rec.Lead_Source_Platform;
    document.getElementById('home_ny').value = lead_rec.Would_you_like_to_buy_a_home_in_NY;
    document.getElementById('first_home').value = lead_rec.Are_you_a_First_Time_Home_Buyer;
    document.getElementById('dream_home').value = lead_rec.Would_help_you_acheive_your_dream_home;
    document.getElementById('payment').value = lead_rec.Do_you_have_between_1_3_for_down_payment;
    document.getElementById('yearly_income').value = lead_rec.What_is_your_yearly_household_income;
    document.getElementById('score').value = lead_rec.What_Range_does_your_credit_score_fall;
    document.getElementById('contact_you').value = lead_rec.When_should_we_contact_you;
    document.getElementById('street').value = lead_rec.Street;
    document.getElementById('City').value = lead_rec.City;
    document.getElementById('state').value = lead_rec.State;
    document.getElementById('zipcode').value = lead_rec.Zip_Code;
    document.getElementById('dob').value = lead_rec.Prospect_DOB;
    document.getElementById('Security_Number').value = lead_rec.Social_Security_Number;
    document.getElementById('Income').value = lead_rec.Annual_Income;
    document.getElementById('Assets').value = lead_rec.Current_Assets;
    document.getElementById('employer').value = lead_rec.Current_Employer;
    document.getElementById('secondary_income').value = lead_rec.Do_you_have_secondary_income;
    document.getElementById('date').value = lead_rec.Start_Date;
    document.getElementById('Veteran').value = lead_rec.Do_you_have_a_VA_benefit;
    document.getElementById('notes').value = lead_rec.Borrower_Notes;
    document.getElementById('co-borrower').checked = lead_rec.Do_you_have_a_co_borrower;
    document.getElementById('b2fname').value = lead_rec.B2_First_Name;
    document.getElementById('b2lname').value = lead_rec.B2_Last_Name;
    document.getElementById('email').value = lead_rec.B2_Email;
    document.getElementById('b2dob').value = lead_rec.B2_DOB;
    document.getElementById('b2_address').value = lead_rec.B2_Address;
    document.getElementById('b2_City').value = lead_rec.B2_City;
    document.getElementById('b2_state').value = lead_rec.B2_State;
    document.getElementById('b2_zipcode').value = lead_rec.B2_Zip_Code;
    document.getElementById('b2_Income').value = lead_rec.B2_Annual_Income;
    document.getElementById('b2_notes').value = lead_rec.Co_Borrower_Notes;
});
ZOHO.embeddedApp.init();